server:
  port: 8066
  tomcat:
    uri-encoding: utf-8

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.bean

spring:
  datasource:

    url: jdbc:mysql://47.120.5.13:3306/jd?zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8 #url
    username: "hd"
    password: "hhd443.."
    driver-class-name: com.mysql.cj.jdbc.Driver
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true

alipay:
  appId: 2021000122601384
  appPrivateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC5Ic+yr4zDcMql42lpSMxKkseaExom1pzaOQTj0bw8h2C5RlqER0od5Z3UAYpTMTTh3W/fMHhRQcJUf6QnY7lHgiC5zGBc4OiqfH3t4h+HNzgxDy/A4fBdGqUkKsqFzFk7z4XiivF/86T/JTSYfCescusZpotAvsIc9nk//yWdw9BcLSBeZs3I893SaccxbXPVLIjP6WUp0Ib8Aca21J1/50hLhLjIDALxbNqNrDdeElN45cN5o5Y91zjI90HJSRGqV1XDP69vEWl4I9OPLejg+TLjPLCIGvbmRrXqB/01Hy/LsMNJA1tVbH7r47hS9NK8VG9bpq28v/DXMMinBGW3AgMBAAECggEBAJuBTB4SmVF9R6sqJ1v5eyhUvHat/vSKprwi0vmuLchGCrf14Yhk/Vu5iOYQ2SjiF0J1p0e5RgczDlG92ZwAhxwKsQSAKJ07ihPSeFC99K+2cWu8DuecoTMDc526l9zldjroKNTO0uYgOQLcNJ61Avo2mUY1f5jF4vVDDzvzTJyD8zlhkFTjPWMy/zNWQi7QiP6Z+gst1P0eDZ3AuhNclXEXL7pzwQ0rGdRxTX0izxvwMTU+C1jpBpS6DTqOA3yR5CztH6kDcbOZjThaL/evbHpk2x0F4L8APRri46XTnoguJyT3yvkVJMBbDFZ8lYjWPpsooA5wW4yZcOzyTMIMTLkCgYEA9CNMrzwHDTUo+Ela1LkKGSXiJT5C7ZcNZZ9+dobLX3yPGQlaO6iPP7zfnHz/RhwNiYuoqAKAt2meJMo+QRG1zrE2WIQQ7hkZynC1MOC1INjGoW3xCB3tTCnmlNIGUSOCeRalBK8DivCKi/dFMkqwK7VYFjm5aFLsocamutflaMMCgYEAwiCR72eQkPW1q5qQpPrzD9X7aH0EWnBSNxMz0L4yIlcMfagYjMDcOdpl/k0qpqSy52AtR3tNHfbJVXOFY0ZmuwT9mzOk/jbKMAduJn0M1xKAU0FFgtg/s2FfLskvhM+f2ekCf/Ow6CL/JBuZaaTvxXBlNFaXOYznSNcvT+Au3/0CgYA7XGXl6cORK47VqAhk1sUkzjhJc/UUDflc70Xxjd7fTcsBfGurO9Xw2nzIcQAkzOdhvUp553nintSr/1zZt3OsWRxss1fmfMXvmi4EP27rGKpbT/8eSSCMt1dwcgzFJ8wuoxnmpKNI4ind1HbHvq9NQV+0r75sJlWRFFsv7RTDvwKBgH2tEE1pQtJWADMEcbgdLtaFtalDplnWdaNqLxVozJQmvtNqy9nz0Z8yoO0tj/sqjRf1z9qDHL3VUyqbCzPmFAPnize7C4n4dpT5eno4YuOp+qHrk9DNpw++bhyf6r+Umuw8SX4Eifb/ESaTJ5KZUREFXr+vf1+mtOUXSm3vuOkRAoGAC10dhghNsUlrhqiSH7a31WT8IFo8cbfhZH08stievyfomo1GygfMAZMnsBLVMc/hacxkLmUC/a4gT96UTz6QadxRMH/I+7jQBlyexCR20efl3Vii1xTnyUg4Ya7nCJDsvRMRKilqxdWKQoGS1fG8aRiMXcpLL0++RQpra9blpb8=
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1IHLko+NlYYyYbn0lDsDl3zw0SunlqpqTVwd8HJ58YK0+iEWN8fVlpF3HfEyWYd93HFvD2uATuRHP9l5Uf9U4Jmb2qtTd+TrpQXiK14jUBz3AVSun+1X3GmVtSRAqamP0FoIhSBWFEgRYpRHrkDiwjmEKp0b6EJcTzoqmU9Aoqj6LR/yDY5GWr6xAcTglKrCARln0LcGHhQoXymMulKZeg49MjmHbGyzVuE7+RXksMehn7zuCKW8AP8VS6AS8FDRdZez73XlcfmnBngDY4jTmbw7s7mfBpZkryWR2uAh1iurXhuHGRms/TVuyKR0pLaG5sjZl9tz8A55aWrJieJLawIDAQAB
  notifyUrl: http://dkn8hc.natappfree.cc/alipay/notify

redis:
  host: localhost
  port: 6379
  lettuce:
    pool:
      max-active: 100
      max-wait: -1ms
      max-idle: 8
      min-idle: 1
  timeout: PT10S
  password: 123456
